function getDTHTranData() {
	return [{
			"group": "1",
			"xh": "1",
			"levtime": "21:00",
			"arrtime": "7:00",
			"adddays": "1",
			"type": "pk",
			"count": "140",
			"levsta": "ddg",
			"arvsta": "dth",
			"trainnum": "37707"
		},
		{
			"group": "1",
			"xh": "2",
			"levtime": "22:30",
			"arrtime": "8:30",
			"adddays": "1",
			"type": "ak",
			"count": "70",
			"levsta": "ddg",
			"arvsta": "dth",
			"trainnum": "37708"
		},
		{
			"group": "2",
			"xh": "1",
			"levtime": "10:00",
			"arrtime": "17:30",
			"adddays": "0",
			"type": "xm",
			"count": "35",
			"levsta": "ddg",
			"arvsta": "sysn",
			"trainnum": "37710"
		},
		{
			"group": "2",
			"xh": "2",
			"levtime": "13:00",
			"arrtime": "20:50",
			"adddays": "0",
			"type": "ak",
			"count": "33",
			"levsta": "ddg",
			"arvsta": "sysn",
			"trainnum": "37711"
		},
		{
			"group": "3",
			"xh": "1",
			"levtime": "20:30",
			"arrtime": "7:30",
			"adddays": "1",
			"type": "xm",
			"count": "55",
			"levsta": "hj",
			"arvsta": "mhk",
			"trainnum": "37704"
		},
		{
			"group": "4",
			"xh": "1",
			"levtime": "17:45",
			"arrtime": "22:40",
			"adddays": "0",
			"type": "j",
			"count": "35",
			"levsta": "mhk",
			"arvsta": "dth",
			"trainnum": "37703"
		},
		{
			"group": "4",
			"xh": "2",
			"levtime": "23:00",
			"arrtime": "9:00",
			"adddays": "1",
			"type": "ak",
			"count": "35",
			"levsta": "mhk",
			"arvsta": "dth",
			"trainnum": "37713"
		},
		{
			"group": "4",
			"xh": "3",
			"levtime": "14:00",
			"arrtime": "19:20",
			"adddays": "0",
			"type": "hm",
			"count": "35",
			"levsta": "mhk",
			"arvsta": "dth",
			"trainnum": "37706"
		},
		{
			"group": "5",
			"xh": "1",
			"levtime": "17:35",
			"arrtime": "1:55",
			"adddays": "1",
			"type": "j",
			"count": "55",
			"levsta": "shg",
			"arvsta": "sysn",
			"trainnum": "37701"
		},
		{
			"group": "6",
			"xh": "1",
			"levtime": "13:20",
			"arrtime": "19:30",
			"adddays": "0",
			"type": "pk",
			"count": "35",
			"levsta": "sysn",
			"arvsta": "mhk",
			"trainnum": "37715"
		},
		{
			"group": "6",
			"xh": "3",
			"levtime": "8:05",
			"arrtime": "14:20",
			"adddays": "0",
			"type": "hm",
			"count": "35",
			"levsta": "sysn",
			"arvsta": "mhk",
			"trainnum": "37702"
		},
		{
			"group": "6",
			"xh": "2",
			"levtime": "15:50",
			"arrtime": "23:40",
			"adddays": "0",
			"type": "j",
			"count": "35",
			"levsta": "sysn",
			"arvsta": "mhk",
			"trainnum": "37702"
		},
		{
			"group": "7",
			"xh": "1",
			"levtime": "23:00",
			"arrtime": "11:20",
			"adddays": "1",
			"type": "hm",
			"count": "35",
			"levsta": "thdq",
			"arvsta": "sysn",
			"trainnum": "37702"
		},
		{
			"group": "8",
			"xh": "1",
			"levtime": "23:00",
			"arrtime": "11:20",
			"adddays": "1",
			"type": "xm",
			"count": "33",
			"levsta": "thzb",
			"arvsta": "dth",
			"trainnum": "37702"
		},
	]
}


	/* [{
			"group": "1",
			"xh": "1",
			"levtime": "21:00",
			"arrtime": "7:00",
			"adddays": "1",
			"type": "pk",
			"count": "35",
			"levsta": "ddg",
			"arvsta": "dth",
			"trainnum": "37707"
		},
		{
			"group": "1",
			"xh": "2",
			"levtime": "22:30",
			"arrtime": "8:30",
			"adddays": "1",
			"type": "ak",
			"count": "35",
			"levsta": "ddg",
			"arvsta": "dth",
			"trainnum": "37708"
		},
		{
			"group": "1",
			"xh": "3",
			"levtime": "3:40",
			"arrtime": "13:40",
			"adddays": "0",
			"type": "pk",
			"count": "35",
			"levsta": "ddg",
			"arvsta": "dth",
			"trainnum": "37709"
		},
		{
			"group": "1",
			"xh": "4",
			"levtime": "21:00",
			"arrtime": "7:00",
			"adddays": "1",
			"type": "pk",
			"count": "35",
			"levsta": "ddg",
			"arvsta": "dth",
			"trainnum": "37707"
		},
		{
			"group": "1",
			"xh": "5",
			"levtime": "22:30",
			"arrtime": "8:30",
			"adddays": "1",
			"type": "ak",
			"count": "35",
			"levsta": "ddg",
			"arvsta": "dth",
			"trainnum": "37708"
		},
		{
			"group": "1",
			"xh": "6",
			"levtime": "3:40",
			"arrtime": "13:40",
			"adddays": "0",
			"type": "pk",
			"count": "35",
			"levsta": "ddg",
			"arvsta": "dth",
			"trainnum": "37709"
		},
		{
			"group": "2",
			"xh": "1",
			"levtime": "10:00",
			"arrtime": "17:30",
			"adddays": "0",
			"type": "xm",
			"count": "35",
			"levsta": "ddg",
			"arvsta": "sysn",
			"trainnum": "37710"
		},
		{
			"group": "2",
			"xh": "2",
			"levtime": "13:00",
			"arrtime": "20:50",
			"adddays": "0",
			"type": "ak",
			"count": "33",
			"levsta": "ddg",
			"arvsta": "sysn",
			"trainnum": "37711"
		},
		{
			"group": "3",
			"xh": "1",
			"levtime": "20:30",
			"arrtime": "7:30",
			"adddays": "1",
			"type": "xm",
			"count": "35",
			"levsta": "hj",
			"arvsta": "mhk",
			"trainnum": "37704"
		},
		{
			"group": "4",
			"xh": "3",
			"levtime": "17:45",
			"arrtime": "22:40",
			"adddays": "0",
			"type": "j",
			"count": "35",
			"levsta": "mhk",
			"arvsta": "dth",
			"trainnum": "37703"
		},
		{
			"group": "4",
			"xh": "2",
			"levtime": "23:00",
			"arrtime": "9:00",
			"adddays": "1",
			"type": "ak",
			"count": "35",
			"levsta": "mhk",
			"arvsta": "dth",
			"trainnum": "37713"
		},
		{
			"group": "4",
			"xh": "4",
			"levtime": "8:00",
			"arrtime": "13:00",
			"adddays": "0",
			"type": "xm",
			"count": "35",
			"levsta": "mhk",
			"arvsta": "dth",
			"trainnum": "37705"
		},
		{
			"group": "4",
			"xh": "3",
			"levtime": "14:00",
			"arrtime": "19:20",
			"adddays": "0",
			"type": "hm",
			"count": "35",
			"levsta": "mhk",
			"arvsta": "dth",
			"trainnum": "37706"
		},
		{
			"group": "5",
			"xh": "1",
			"levtime": "17:35",
			"arrtime": "1:55",
			"adddays": "1",
			"type": "j",
			"count": "55",
			"levsta": "shg",
			"arvsta": "sysn",
			"trainnum": "37701"
		},
		{
			"group": "6",
			"xh": "1",
			"levtime": "13:20",
			"arrtime": "19:30",
			"adddays": "0",
			"type": "pk",
			"count": "35",
			"levsta": "sysn",
			"arvsta": "mhk",
			"trainnum": "37715"
		},
		{
			"group": "6",
			"xh": "4",
			"levtime": "8:05",
			"arrtime": "14:20",
			"adddays": "0",
			"type": "hm",
			"count": "35",
			"levsta": "sysn",
			"arvsta": "mhk",
			"trainnum": "37702"
		},
		{
			"group": "6",
			"xh": "2",
			"levtime": "2:20",
			"arrtime": "10:40",
			"adddays": "0",
			"type": "ak",
			"count": "35",
			"levsta": "sysn",
			"arvsta": "mhk",
			"trainnum": "37713"
		},
		{
			"group": "6",
			"xh": "3",
			"levtime": "15:50",
			"arrtime": "23:40",
			"adddays": "0",
			"type": "j",
			"count": "35",
			"levsta": "sysn",
			"arvsta": "mhk",
			"trainnum": "37702"
		},
		{
			"group": "7",
			"xh": "1",
			"levtime": "23:00",
			"arrtime": "11:20",
			"adddays": "1",
			"type": "hm",
			"count": "35",
			"levsta": "thdq",
			"arvsta": "sysn",
			"trainnum": "37702"
		},
		{
			"group": "8",
			"xh": "1",
			"levtime": "23:00",
			"arrtime": "11:20",
			"adddays": "1",
			"type": "xm",
			"count": "33",
			"levsta": "thzb",
			"arvsta": "dth",
			"trainnum": "37702"
		},
	] */